export const ActionTypes = {
    SET_ITEMS: "SET_ITEMS",
    DEL_ITEMS: "DEL_ITEMS",
    SET_RESULTS: "SET_RESULTS",
    DEL_RESULTS: "DEL_RESULTS",
    SET_SEARCH: "SET_SEARCH",
    DEL_SEARCH: "DEL_SEARCH",
    SELECTED_ITEM: "SELECTED_ITEM",
    REMOVE_SELECTED_ITEM: "REMOVE_SELECTED_ITEM",
};